### ISSUE TITLE
error: cannot GET /

### ISSUE THREAD

**Issue by JohnAllenB** [barrycumbie/ubiquitous-umbrella-dev#19]
@barrycumbie I added index, style, script files to my lab and got them connecting and working locally. I then committed the changes and tried to deploy the latest commit on render.com. I ended up getting the error "cannot GET /" Any idea on what this means? 

<img width="1440" alt="Screenshot 2024-08-28 at 4 44 44 PM" src="https://github.com/user-attachments/assets/6392c2d5-b632-4f15-be96-3479a8c23c61">

**Comment by JohnAllenB** [comment]
Figured it out, not sure how.

**Comment by barrycumbie** [comment]
😎 
Glad I could help
