### ISSUE TITLE
dual boot linux

### ISSUE THREAD

**Issue by barrycumbie** [barrycumbie/ubiquitous-umbrella-dev#5]
1️⃣  reboot and select Ubuntu from the boot menu

2️⃣ login with your una credentials including the `_FULL REALM_`

For example: `fflintstone@main.local.una.edu` and press <kbd>enter</kbd>, then type your password

**Comment by barrycumbie** [comment]
@barrycumbie the linux box won't let anyone install anything without the password for 'labroot'.

please give me admin and/or super user privledges.

**Comment by v-sec0** [comment]
**to install vscode:**
1. go to vscode website and install for deb
2. open terminal
3. go to downloads folder (`cd ~/Downloads`)
4. enter `sudo apt install ./{vscode-file-name}.deb`
