### ISSUE TITLE
can't install vscode in linux

### ISSUE THREAD

**Issue by v-sec0** [barrycumbie/ubiquitous-umbrella-dev#9]
@barrycumbie the linux box won't let anyone install anything without the password for 'labroot'. 

please give me admin and/or super user privledges.

**Comment by barrycumbie** [comment]
see #5

**Comment by v-sec0** [comment]
i do have sudo, just wasn't able to install from software store.

oopsie!

**Comment by barrycumbie** [comment]
`sudo snap install code --classic `
